version: '3.8'
services:
  server:
    build: ./backend
    container_name: server_container
    ports:
      - '5000:5000'
  cilent:
    build: ./frontend
    container_name: client_container
    ports:
      - '3000:3000'
    stdin_open: true
    tty: true
  database:
    image: mongo
    container_name: database_container
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local